development:
  adapter: postgresql
  encoding: unicode
  database: gitfeats_development
  pool: 5
  host: localhost
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: gitfeats_test
  pool: 5
  host: localhost
  password:
